name = "LazyArrays"
uuid = "5078a376-72f3-5289-bfd5-ec5146d43c02"
version = "2.6.2"

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
LazyArraysBandedMatricesExt = "BandedMatrices"
LazyArraysBlockArraysExt = "BlockArrays"
LazyArraysBlockBandedMatricesExt = "BlockBandedMatrices"
LazyArraysStaticArraysExt = "StaticArrays"

[compat]
Aqua = "0.8"
ArrayLayouts = "1.10.1"
BandedMatrices = "1.6.2"
Base64 = "1"
BlockArrays = "1.0"
BlockBandedMatrices = "0.13"
FillArrays = "1.0"
Infinities = "0.1"
LinearAlgebra = "1"
MacroTools = "0.5"
Random = "1.0"
SparseArrays = "1"
StaticArrays = "1.0"
Test = "1"
Tracker = "0.2"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
Infinities = "e1ba4f0e-776d-440f-acd9-e1d2e9742647"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"

[targets]
test = ["Aqua", "BandedMatrices", "Base64", "BlockArrays", "BlockBandedMatrices", "StaticArrays", "Tracker", "Test", "Infinities", "Random"]
